Доработана функциональность в соотвествии с ТЗ 6 спринта
KseniaYakovenko/java-kanban pull request #1
Opened 2024-02-23 20:02 UTC by KseniaYakovenko

Переработан механизм хранения и функционирования истории InMemoryHistoryManager.

2024-02-25 08:14 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-02-25 08:14 UTC, LexLippi commented on src/service/InMemoryHistoryManager.java
> +    Node last;
Не хватает модификаторов доступа

2024-02-25 08:14 UTC, LexLippi commented on src/service/InMemoryHistoryManager.java
> +        if (oldLast == null)
В соответствии с Java Google Code Style советую оставлять фигурные скобки, даже если они опциональные:

https://google.github.io/styleguide/javaguide.html#s4.1.1-braces-always-used

2024-02-25 08:14 UTC, LexLippi commented on src/service/InMemoryHistoryManager.java
> +        ArrayList<Task> history = new ArrayList<>();
Так как мы убрали ограничение на размер истории, то лучше использовать `LinkedList`, так как добавление в него работает за `O(1)` в худшем случае, а добавление в `ArrayList` за `O(n)` в худшем случае.

https://www.baeldung.com/java-arraylist-linkedlist

2024-02-25 08:14 UTC, LexLippi commented on src/service/InMemoryHistoryManager.java
> +            nodeForDelete.prev = null;
Эта строка по факту ничего не делает, поскольку gc удалит этот объект вне зависимости от удаления данной ссылки

2024-02-25 08:14 UTC, LexLippi commented on src/service/InMemoryHistoryManager.java
> +            nodeForDelete.next = null;
Аналогично тому, что написал выше

2024-02-25 08:14 UTC, LexLippi commented on src/service/InMemoryHistoryManager.java
> +        nodeForDelete.item = null;
Аналогично тому, что написал выше

2024-02-25 11:56 UTC, KseniaYakovenko commented on src/service/InMemoryHistoryManager.java
> +    Node last;
Добавила

2024-02-25 11:58 UTC, KseniaYakovenko commented on src/service/InMemoryHistoryManager.java
> +        if (oldLast == null)
Исправила

2024-02-25 12:04 UTC, KseniaYakovenko commented on src/service/InMemoryHistoryManager.java
> +        ArrayList<Task> history = new ArrayList<>();
Исправила

2024-02-25 12:07 UTC, KseniaYakovenko commented on src/service/InMemoryHistoryManager.java
> +            nodeForDelete.prev = null;
Исправила

2024-02-25 12:07 UTC, KseniaYakovenko commented on src/service/InMemoryHistoryManager.java
> +            nodeForDelete.next = null;
Исправила

2024-02-25 12:08 UTC, KseniaYakovenko commented on src/service/InMemoryHistoryManager.java
> +        nodeForDelete.item = null;
Исправила

2024-02-26 07:37 UTC, LexLippi approved these changes
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2024-03-04 20:53 UTC, merged