Sprint 7
KseniaYakovenko/java-kanban pull request #2
Opened 2024-03-08 02:59 UTC by KseniaYakovenko

2024-03-08 11:52 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-03-08 11:52 UTC, LexLippi commented on src/model/SubTask.java
> +        this.epic = null;
Эта строчка необязательна. По умолчанию поле будет инициализировано именно, как `null`

2024-03-08 11:52 UTC, LexLippi commented on src/model/TaskData.java
> +    final List<Task> history;
Модификатор доступа должен быть `private`

2024-03-08 11:52 UTC, LexLippi commented on src/repository/CsvTaskRepository.java
> +    private static final String HISTORY_CSV = "history.csv";
Такие данные лучше не зашивать, как константу, а передавать в качестве аргумента

2024-03-08 11:52 UTC, LexLippi commented on src/service/InMemoryTaskManager.java
> +    }
Хотелось бы понять почему этот метод нужен, если он пустой. И нужен ли он вообще

2024-03-08 11:52 UTC, LexLippi commented on src/service/InMemoryTaskManager.java
> +    protected HashMap<Integer, Task> tasks = new HashMap<>();
Необходим модификатор `final`

2024-03-08 11:52 UTC, LexLippi commented on src/repository/CsvTaskRepository.java
> +            System.out.println(historyLine);
Отладочные принты лучше убирать из получившегося кода

2024-03-08 11:52 UTC, LexLippi commented on src/repository/CsvTaskRepository.java
> +        Task task;
Не очень понятно зачем создавать общую переменную, если мы не используем ее нигде после `switch`, в таком случае в каждой ветке можно создать свою переменную с таким названием и не отрывать инициализацию от объявления

2024-03-08 11:52 UTC, LexLippi commented on src/repository/CsvTaskRepository.java
> +                }
Можно воспользоваться тернарным оператором

2024-03-08 11:52 UTC, LexLippi commented on src/repository/CsvTaskRepository.java
> +                        taskData.getHistory().add(fullMap.get(id));
Что если произошла ошибка при заполнении и `fullMap` не содержит такого идентификатора?

2024-03-08 16:33 UTC, KseniaYakovenko commented on src/model/SubTask.java
> +        this.epic = null;
Убрала

2024-03-08 16:35 UTC, KseniaYakovenko commented on src/model/TaskData.java
> +    final List<Task> history;
Исправила

2024-03-08 17:20 UTC, KseniaYakovenko commented on src/repository/CsvTaskRepository.java
> +    private static final String HISTORY_CSV = "history.csv";
Добавила через реализацую интрефейса FileProvider

2024-03-08 17:24 UTC, KseniaYakovenko commented on src/service/InMemoryTaskManager.java
> +    }
Убрала, при разработке и тестировании использовался

2024-03-08 17:25 UTC, KseniaYakovenko commented on src/service/InMemoryTaskManager.java
> +    protected HashMap<Integer, Task> tasks = new HashMap<>();
Добавила

2024-03-08 17:26 UTC, KseniaYakovenko commented on src/repository/CsvTaskRepository.java
> +            System.out.println(historyLine);
Убрала

2024-03-08 17:33 UTC, KseniaYakovenko commented on src/repository/CsvTaskRepository.java
> +        Task task;
Спасибо, разделила по веткам switch

2024-03-08 17:42 UTC, KseniaYakovenko commented on src/repository/CsvTaskRepository.java
> +                }
Спасибо, поправила

2024-03-08 18:19 UTC, KseniaYakovenko commented on src/repository/CsvTaskRepository.java
> +                        taskData.getHistory().add(fullMap.get(id));
Добавила выброс исключения с сообщением о проблеме при загрузки истории и информацией о id. Спасибо.

2024-03-09 19:21 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2024-03-24 10:21 UTC, merged