Sprint 8
KseniaYakovenko/java-kanban pull request #3
Opened 2024-03-25 12:48 UTC by KseniaYakovenko

Добавлен функционал в соответствии с техническим заданием спринта 8.

2024-03-26 07:24 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть пара небольших замечаний, которые необходимо исправить!

Желаю удачи!

2024-03-26 07:24 UTC, LexLippi commented on src/model/Epic.java
> +        return (LocalDateTime) minDate.get();
1. Не стоит использовать `Optional` без `generic`-параметра
2. Это можно написать немного правильнее. Вообще, при работе с `Optional` надо по возможности избегать метода `get`, так как он нарушает ленивость операций
3. 
```java
return subTasks.stream()
        .max(Comparator.comparing(SubTask::getStartTime))
        .map(Task::getStartTime)
        .orElseGet(() -> super.getStartTime());
```

2024-03-26 07:24 UTC, LexLippi commented on test/repository/BadCsvFileNameProviderTest.java
> +public class BadCsvFileNameProviderTest implements FileNameProvider {
Если это файлы не содержащие тестов, то лучше не использовать для них суффикс `Test`

2024-03-26 14:23 UTC, KseniaYakovenko commented on test/repository/BadCsvFileNameProviderTest.java
> +public class BadCsvFileNameProviderTest implements FileNameProvider {
Исправила.

2024-03-26 14:39 UTC, KseniaYakovenko commented on src/model/Epic.java
> +        return (LocalDateTime) minDate.get();
Спасибо, исправила. Заодно исправила багу у себя в логике расчета endTime у Epic.

2024-03-27 13:56 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2024-04-06 10:22 UTC, merged